version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: 18er0821
      MONGO_INITDB_DATABASE: eccomerce
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    volumes:
      - './data:/data/db'
